CREATE TABLE `tbl_noticias_blog` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`titulo` MEDIUMTEXT NOT NULL,
	`dcorta` MEDIUMTEXT NOT NULL,
	`dlarga` LONGTEXT NOT NULL,
	`estatus` VARCHAR(50) NOT NULL DEFAULT 'importante',
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=4
;
