CREATE TABLE `tblnoticias_submenu` (
	`idopcion` INT(10) UNSIGNED NOT NULL,
	`idsubmenu` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`PosS` INT(10) UNSIGNED NOT NULL,
	`url` VARCHAR(100) NOT NULL,
	`descripcion` VARCHAR(45) NOT NULL,
	`estado` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1',
	`glyphicon` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`idopcion`, `idsubmenu`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
;
