CREATE TABLE `tblnoticias_menu` (
	`idopcion` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`descripcion` VARCHAR(45) NOT NULL,
	`PosI` INT(10) UNSIGNED NOT NULL,
	`glyphicon` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`idopcion`)
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
AUTO_INCREMENT=100
;
